title: Dominik Kemmer
description: M.A. and M.Sc.

url: 
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: Location
    url: /location
  - title: Schedule
    url: /schedule
  - title: About the Organizers
    url: /contact

social:
  github: ESTML
  twitter:  
  facebook:  
  email: carolin.mueller@ext.uni.lu
  linkedin:  

google_analytics: "UA-58263416-1"


