title: Dominik Kemmer
description: M.A. and M.Sc.

url: 
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: Coaching und Beratung
    url: /coaching
  - title: Über mich
    url: /cv
  - title: Kontakt
    url: /contact

social:
  github: https://github.com/distinkt-consulting
  #twitter: 
  #facebook:  
  email: webmaster@distinkt.de
  linkedin: https://www.linkedin.com/in/dominik-kemmer-aa526596

google_analytics: "UA-58263416-1"


